# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-06-11 04:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20180601_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='m2m',
            field=models.ManyToManyField(to='app01.Role', verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='ug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.UserGroup', verbose_name='用户组'),
        ),
    ]
