# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-06-11 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraapp', '0002_auto_20180611_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, null=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, null=True, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='邮箱')),
                ('roles', models.ManyToManyField(blank=True, null=True, to='extraapp.Role', verbose_name='拥有角色')),
            ],
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='m2m',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='ug',
        ),
        migrations.DeleteModel(
            name='UserGroup',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
